services:
  account-db:
    image: postgres:16
    container_name: account-db
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: account_pass
    volumes:
      - account_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - account_db_network
      - store_front_network

  account-service:
    build: .
    container_name: account-service
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    environment:
      DB_NAME: account_db
      DB_USER: account_user
      DB_PASSWORD: account_pass
      DB_HOST: account-db
      DB_PORT: 5432
    depends_on:
      - account-db
    networks:
      - account_db_network
      - store_front_network

volumes:
  account_db_data:

networks:
  account_db_network:
    driver: bridge
  store_front_network:
    external: true
