# Generated by Django 5.2.4 on 2026-03-03 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = []
