services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - store_front_network

  global-redis:
    image: redis:7-alpine
    container_name: global-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - store_front_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # healthcheck:
    #   test: ["CMD", "rabbitmqctl", "status"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    networks:
      - store_front_network

  account-db:
    image: postgres:16-alpine
    container_name: account-db
    environment:
      POSTGRES_DB: ${ACCOUNT_DB_NAME:-account_db}
      POSTGRES_USER: ${ACCOUNT_DB_USER:-account_user}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD:-account_pass}
    ports:
      - "5432:5432"
    volumes:
      - account_db_data:/var/lib/postgresql/data
    networks:
      - store_front_network

  catalogue-db:
    image: postgres:16-alpine
    container_name: catalogue-db
    environment:
      POSTGRES_DB: ${CATALOGUE_DB_NAME:-catalogue_db}
      POSTGRES_USER: ${CATALOGUE_DB_USER:-catalogue_user}
      POSTGRES_PASSWORD: ${CATALOGUE_DB_PASSWORD:-catalogue_pass}
    ports:
      - "5433:5432"
    volumes:
      - catalogue_db_data:/var/lib/postgresql/data
    networks:
      - store_front_network

  orders-db:
    image: postgres:16-alpine
    container_name: orders-db
    environment:
      POSTGRES_DB: ${ORDERS_DB_NAME:-orders_db}
      POSTGRES_USER: ${ORDERS_DB_USER:-orders_user}
      POSTGRES_PASSWORD: ${ORDERS_DB_PASSWORD:-orders_pass}
    ports:
      - "5434:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    networks:
      - store_front_network

  billing-db:
    image: postgres:16-alpine
    container_name: billing-db
    environment:
      POSTGRES_DB: ${BILLING_DB_NAME:-billing_db}
      POSTGRES_USER: ${BILLING_DB_USER:-billing_user}
      POSTGRES_PASSWORD: ${BILLING_DB_PASSWORD:-billing_pass}
    ports:
      - "5425:5432"
    volumes:
      - billing_db_data:/var/lib/postgresql/data
    networks:
      - store_front_network

  account-service:
    build:
      context: ./services/account_service
      dockerfile: Dockerfile
    container_name: account-service
    command: >
      sh -c "python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn core.wsgi:application --config gunicorn.conf.py"
    environment:
      USE_PG: ${USE_PG:-true}
      DB_NAME: ${DB_NAME:-account_db}
      DB_USER: ${DB_USER:-account_user}
      DB_PASSWORD: ${DB_PASSWORD:-account_pass}
      DB_HOST: account-db
      # DB_PORT: ${DB_PORT:-5432}
      DATABASE_URL: postgresql://${DB_USER:-account_user}:${DB_PASSWORD:-account_pass}@account-db:5432/${DB_NAME:-account_db}
      # Credentials du superuser (CHANGEZ-LES EN PRODUCTION!)
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-admin}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-admin}
      # DJANGO_SUPERUSER_ROLE: ADMIN
      REDIS_URL: redis://${REDIS_HOST:-global-redis}:6379/1
    ports:
      - "8000:8000"
    depends_on:
      - account-db
      - global-redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.accounts.rule=(Host(`api.localhost`) || Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/api/v1/accounts`)
      - traefik.http.routers.accounts.entrypoints=web
      - traefik.http.services.accounts.loadbalancer.server.port=8000
      - traefik.docker.network=store_front_network
      - traefik.http.middlewares.accounts-stripprefix.stripprefix.prefixes=/api/v1/accounts
      - traefik.http.routers.accounts.middlewares=accounts-stripprefix
    volumes:
      - ./services/account_service:/app
    networks:
      - store_front_network

  catalogue-service:
    build:
      context: ./services/product_service
      dockerfile: Dockerfile
    container_name: catalogue-service
    command: >
      sh -c "python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn core.wsgi:application --config gunicorn.conf.py"
    environment:
      USE_PG: ${USE_PG:-true}
      DATABASE_URL: postgresql://${CATALOGUE_DB_USER:-catalogue_user}:${CATALOGUE_DB_PASSWORD:-catalogue_pass}@catalogue-db:5432/${CATALOGUE_DB_NAME:-catalogue_db}
      DB_HOST: catalogue-db
      # DB_PORT: "5432"
      REDIS_URL: redis://global-redis:6379/2
      # RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER:-admin}:${RABBITMQ_DEFAULT_PASS:-admin}@rabbitmq:5672/
      JWT_ISSUER: ${JWT_ISSUER:-account-service}
      JWT_AUDIENCE: ${JWT_AUDIENCE:-store-front-services}
    ports:
      - "8001:8000"
    depends_on:
      - catalogue-db
      - global-redis
      # - rabbitmq
    labels:
      - traefik.enable=true
      - traefik.http.routers.catalogue.rule=(Host(`api.localhost`) || Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/api/v1/catalogue`)
      - traefik.http.middlewares.catalogue-stripprefix.stripprefix.prefixes=/api/v1/catalogue
      - traefik.http.routers.catalogue.middlewares=catalogue-stripprefix
      - traefik.http.routers.catalogue.entrypoints=web
      - traefik.http.services.catalogue.loadbalancer.server.port=8000
      - traefik.docker.network=store_front_network
    volumes:
      - ./services/product_service:/app
    networks:
      - store_front_network

  orders-service:
    build:
      context: ./services/order_service
      dockerfile: Dockerfile
    container_name: orders-service
    command: >
      sh -c "python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn core.wsgi:application --config gunicorn.conf.py"
    environment:
      USE_PG: "true"
      DATABASE_URL: postgresql://${ORDERS_DB_USER:-orders_user}:${ORDERS_DB_PASSWORD:-orders_pass}@orders-db:5432/${ORDERS_DB_NAME:-orders_db}
      DB_HOST: orders-db
      # DB_PORT: "5432"
      CATALOGUE_SERVICE_URL: http://catalogue-service:8000
      ACCOUNT_SERVICE_URL: http://account-service:8000
      REDIS_URL: redis://global-redis:6379/3
      CELERY_BROKER_URL: redis://global-redis:6379/0
      CELERY_RESULT_BACKEND: redis://global-redis:6379/0
      CELERY_TIMEZONE: Africa/Douala
      JWT_ISSUER: ${JWT_ISSUER:-account-service}
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER:-admin}:${RABBITMQ_DEFAULT_PASS:-admin}@rabbitmq:5672/
      JWT_AUDIENCE: ${JWT_AUDIENCE:-store-front-services}
    ports:
      - "8002:8000"
    depends_on:
      - orders-db
      - catalogue-service
      - account-service
      - global-redis
      - rabbitmq
    labels:
      - traefik.enable=true
      - traefik.http.routers.orders.rule=(Host(`api.localhost`) || Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/api/v1/orders`)
      - traefik.http.middlewares.orders-stripprefix.stripprefix.prefixes=/api/v1/orders
      - traefik.http.routers.orders.middlewares=orders-stripprefix
      - traefik.http.routers.orders.entrypoints=web
      - traefik.http.services.orders.loadbalancer.server.port=8000
      - traefik.docker.network=store_front_network
    volumes:
      - ./services/order_service:/app
    networks:
      - store_front_network

  orders-worker:
    build:
      context: ./services/order_service
      dockerfile: Dockerfile
    container_name: orders-worker
    command: celery -A core worker -l info --hostname=orders@%h --queues=orders
    environment:
      USE_PG: "true"
      DATABASE_URL: postgresql://${ORDERS_DB_USER:-orders_user}:${ORDERS_DB_PASSWORD:-orders_pass}@orders-db:5432/${ORDERS_DB_NAME:-orders_db}
      DB_HOST: orders-db
      # DB_PORT: "5434"
      CATALOGUE_SERVICE_URL: http://catalogue-service:8000
      ACCOUNT_SERVICE_URL: http://account-service:8000
      REDIS_URL: redis://global-redis:6379/3
      CELERY_BROKER_URL: redis://global-redis:6379/0
      CELERY_RESULT_BACKEND: redis://global-redis:6379/0
      CELERY_TIMEZONE: Africa/Douala
      JWT_ISSUER: ${JWT_ISSUER:-account-service}
      JWT_AUDIENCE: ${JWT_AUDIENCE:-store-front-services}
    depends_on:
      - orders-db
      - global-redis
    volumes:
      - ./services/order_service:/app
    networks:
      - store_front_network


  billing-service:
    build:
      context: ./services/billing_service
      dockerfile: Dockerfile

    container_name: billing-service

    command:  [
      "uvicorn",
      "app.main:app",
      "--host",
      "0.0.0.0",
      "--port",
      "8000"
      ]

    environment:
      DATABASE_URL: postgresql://${BILLING_DB_USER:-billing_user}:${BILLING_DB_PASSWORD:-billing_pass}@billing-db:5432/${BILLING_DB_NAME:-billing_db}

      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER:-admin}:${RABBITMQ_DEFAULT_PASS:-admin}@rabbitmq:5672/

    restart: unless-stopped

    ports:
      - "8004:8000"

    depends_on:
      - billing-db
      - rabbitmq

    labels:
      - traefik.enable=true
      - traefik.http.routers.billing.rule=(Host(`api.localhost`) || Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/api/v1/billing`)
      - traefik.http.middlewares.billing-stripprefix.stripprefix.prefixes=/api/v1/billing
      - traefik.http.routers.billing.middlewares=billing-stripprefix
      - traefik.http.routers.billing.entrypoints=web
      - traefik.http.services.billing.loadbalancer.server.port=8000
      - traefik.docker.network=store_front_network

    volumes:
      - ./services/billing_service:/app

    networks:
      - store_front_network

  flower:
    image: mher/flower:2.0.1
    container_name: flower
    command: celery flower --port=5555 --broker=redis://global-redis:6379/0
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://global-redis:6379/0}
      FLOWER_UNAUTHENTICATED_API: "true"
    depends_on:
      - global-redis
    ports:
      - "5555:5555"
    networks:
      - store_front_network


volumes:
  rabbitmq_data:
  billing_db_data:
  account_db_data:
  catalogue_db_data:
  orders_db_data:

networks:
  store_front_network:
    name: store_front_network
    driver: bridge
