services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - store_front_network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  store_front_network:
    # name: store_front_network
    # driver: bridge
    external: true
