services:
  consul:
    image: consul:1.15.4
    container_name: consul
    # command: agent -dev -client=0.0.0.0 -ui
    command: agent -dev -client=0.0.0.0 -ui -config-dir=/consul/config
    volumes:
      - ./config:/consul/config
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
    networks:
      - store_front_network

networks:
  store_front_network:
    external: true
