services:
  orders-db:
    image: postgres:16
    container_name: orders-db
    environment:
      POSTGRES_DB: ${DB_NAME:-orders_db}
      POSTGRES_USER: ${DB_USER:-orders_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-orders_pass}
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXPOSE_PORT:-5434}:5432"
    networks:
      - orders_db_network
      - store_front_network

  orders-service:
    build: .
    container_name: orders-service
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "${ORDERS_SERVICE_PORT:-8002}:8000"
    environment:
      USE_PG: ${USE_PG:-true}
      DB_NAME: ${DB_NAME:-orders_db}
      DB_USER: ${DB_USER:-orders_user}
      DB_PASSWORD: ${DB_PASSWORD:-orders_pass}
      DB_HOST: orders-db
      DB_PORT: ${DB_PORT:-5432}
      DATABASE_URL: postgresql://${DB_USER:-orders_user}:${DB_PASSWORD:-orders_pass}@orders-db:5432/${DB_NAME:-orders_db}
      CATALOGUE_SERVICE_URL: http://catalogue-service:8000
      ACCOUNT_SERVICE_URL: ${ACCOUNT_SERVICE_URL:-http://account-service:8000}
      # RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672/}
    depends_on:
      - orders-db
      # - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.orders.rule=Host(`orders.localhost`)
      - traefik.http.services.orders.loadbalancer.server.port=8000
      - "traefik.docker.network=store_front_network"
      - "traefik.http.routers.orders.entrypoints=web"
    networks:
      - orders_db_network
      - store_front_network
  # redis:
  #   image: redis:7
  #   container_name: redis-orders
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - store_front_network

volumes:
  orders_db_data:

networks:
  orders_db_network:
    driver: bridge
  store_front_network:
    external: true
