# Generated by Django 5.2.4 on 2026-04-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_emptyuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmptyUser",
        ),
    ]