# Generated by Django 6.0.6 on 2026-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_delete_emptyuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reserved_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
