# Generated by Django 5.2.4 on 2026-03-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_order_orderitem_delete_produit"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmptyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
            ],
        ),
    ]
