# Generated by Django 5.2.4 on 2026-04-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_emptyuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client_name",
            field=models.CharField(default="iconnue", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="user_name",
            field=models.CharField(default=str, max_length=150),
            preserve_default=False,
        ),
    ]
