services:
  message-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-service

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.message.rule=Host(`message.localhost`)"
      - "traefik.http.services.message.loadbalancer.server.port=8000"
      - "traefik.docker.network=store_front_network"

    environment:
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}

    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - store_front_network

networks:
  store_front_network:
    external: true
