# Generated by Django 5.2.4 on 2026-03-06 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_category_product_supplier_delete_produit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="suppliers",
        ),
        migrations.AddField(
            model_name="product",
            name="suppliers",
            field=models.ForeignKey(
                default="174ec6ca-79c4-421d-83f2-c8ced50e77a2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="app.supplier",
            ),
            preserve_default=False,
        ),
    ]
